import { Inter } from 'next/font/google'
import './globals.scss'
import StoreProvider from './provider'
import { Toaster } from 'react-hot-toast'
import Navbar from '@/components/Home/Navbar'
import { ThemeWrapper } from './themewrapper'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <StoreProvider>
        <ThemeWrapper>
          <Navbar />
          <Toaster />
          {children}
        </ThemeWrapper>
      </StoreProvider>
    </html>
  )
}
